// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqSB2w1CBAxSnKqJSGJb-5dYSlqKwqxRo',
    appId: '1:206431804311:web:d7739900e0dd975e9982d2',
    messagingSenderId: '206431804311',
    projectId: 'trial-otp-23ae3',
    authDomain: 'trial-otp-23ae3.firebaseapp.com',
    storageBucket: 'trial-otp-23ae3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrFE6Zn-eMmXoBwXUSxC9S9uzYaYKG4ZQ',
    appId: '1:206431804311:android:c62750273badbe9f9982d2',
    messagingSenderId: '206431804311',
    projectId: 'trial-otp-23ae3',
    storageBucket: 'trial-otp-23ae3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZz2eLZPXwXBqUoP49L_zaOvkeGZbOajQ',
    appId: '1:206431804311:ios:e377d098fbe47abb9982d2',
    messagingSenderId: '206431804311',
    projectId: 'trial-otp-23ae3',
    storageBucket: 'trial-otp-23ae3.appspot.com',
    iosBundleId: 'com.example.trialOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZz2eLZPXwXBqUoP49L_zaOvkeGZbOajQ',
    appId: '1:206431804311:ios:e377d098fbe47abb9982d2',
    messagingSenderId: '206431804311',
    projectId: 'trial-otp-23ae3',
    storageBucket: 'trial-otp-23ae3.appspot.com',
    iosBundleId: 'com.example.trialOtp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqSB2w1CBAxSnKqJSGJb-5dYSlqKwqxRo',
    appId: '1:206431804311:web:c405cf5daef4d7689982d2',
    messagingSenderId: '206431804311',
    projectId: 'trial-otp-23ae3',
    authDomain: 'trial-otp-23ae3.firebaseapp.com',
    storageBucket: 'trial-otp-23ae3.appspot.com',
  );
}
